server:
  port: 8888

jdbc:
  driver: com.mysql.jdbc.Driver
  username: root
  password:

spring:
  servlet:
    multipart:
      maxFileSize: -1
      maxRequestSize: -1
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://localhost:3306/drgs?characterEncoding=utf8&serverTimezone=Asia/Shanghai&zeroDateTimeBehavior=convertToNull
      username: root
      password:
      max-active: 20
      max-wait: 6000
      min-idle: 1
      test-on-borrow: true
      test-on-return: true

mybatis:
  mapper-locations: classpath*:com/drgs/mapper/*/*Mapper.xml
  config-location: classpath:MyBatisConfig.xml

redis:
  max:
    total: 20
    idle: 10

  min:
    idle: 2
  test:
    borrow: true
    return: true
  ip: 114.55.103.66
  port: 6379
  password: Lidazui521438

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: countSql


